### ISSUE TITLE
Linux: Incorrectly parsing date from PS output

### ISSUE THREAD

**Issue by Joholland** [profesorfalken/jProcesses#15]
Platform: Amazon Linux

When running getProcesses, I get several Severe warnings about unparseable dates:

```
2016-07-21_01:17:32.52281 SEVERE: null
2016-07-21_01:17:32.52282 java.text.ParseException: Unparseable date: "20 Wed Jul 20 00:39:23"
2016-07-21_01:17:32.52282       at java.text.DateFormat.parse(DateFormat.java:366)
2016-07-21_01:17:32.52282       at org.jutils.jprocesses.util.ProcessesUtils.parseUnixLongTimeToFullDate(ProcessesUtils.java:162)
2016-07-21_01:17:32.52282       at org.jutils.jprocesses.info.UnixProcessesService.parseList(UnixProcessesService.java:68)
2016-07-21_01:17:32.52282       at org.jutils.jprocesses.info.AbstractProcessesService.getList(AbstractProcessesService.java:54)
2016-07-21_01:17:32.52283       at org.jutils.jprocesses.info.AbstractProcessesService.getList(AbstractProcessesService.java:46)
```

 The issue is that the return from `ps` looks like this:

```
 3139 root       4312  1436  0.0   Jul 20 Wed Jul 20 00:40:42 2016 00:00:00   0 mingetty
 3141 root       4312  1488  0.0   Jul 20 Wed Jul 20 00:40:42 2016 00:00:00   0 mingetty
 3145 root       6460  1636  0.0   Jul 20 Wed Jul 20 00:40:42 2016 00:00:00   0 agetty
 4144 root     196440 10744  0.0   Jul 20 Wed Jul 20 01:14:56 2016 00:00:13   0 qualys-cloud-ag
11588 root          0     0  0.0   Jul 20 Wed Jul 20 08:02:01 2016 00:00:01   0 kworker/1:0
14233 root          0     0  0.0 00:56:47 Thu Jul 21 00:56:47 2016 00:00:00   0 kworker/u30:2
14560 shipit   3399444 169180 0.1 01:05:31 Thu Jul 21 01:05:31 2016 00:01:40  0 java
14960 root          0     0  0.0 15:05:31 Thu Jul 21 15:05:31 2016 00:00:00   0 kworker/1:2
```

The bug happens because not every row has a `start` parameter, and on the code that captures the date doesn't grab the correct index in the space split string. I haven't tested enough to see if it happens when `start` is missing, or if it happens when `start` is populated. Only that it happens :)

**Comment by profesorfalken** [comment]
Hi, 

Thanks for reporting it. I will take it a look in the next days.

Regards

**Comment by profesorfalken** [comment]
Hello again, 

In fact what I see in your output is that the start parameter is always there. However sometimes it comes in hh:mm:ss format and sometimes in MMM dd format (Jul 20).

That causes the error in parsing.

**Comment by profesorfalken** [comment]
I have made a fix removing start param in command because it is useless since it is included in lstart. Cant you check if it work? 

https://oss.sonatype.org/content/repositories/snapshots/org/jprocesses/jProcesses/1.6-SNAPSHOT/jProcesses-1.6-20160723.121533-1.jar

Thanks

**Comment by Joholland** [comment]
I've reviewed the commit and this looks like it should fix things. 

You should have a test case for it though ;)

Can you release a non snapshot version of 1.6 now?

Also, I noticed you are now assembling a fat jar. I'd only recommend this for applications. With libraries you remove the ability for users to work around transitive jar issues when you do this.

**Comment by profesorfalken** [comment]
Hello, 
If it is Ok for you, I am going to merge&push to master and prepare the 1.6 version. I will take several hours to be replicated on Maven Central.
The current tests for jProcesses are lazy and only check that the list of processes is populated but not the details. Moreover, this change is internal and does not affect the interface/output (the same fields as before are returned).

Yes I have a maven profile (_with-dependecies_) to create a fat jar, which I use sometimes for other _static_ applications. However, if we do not use this profile explicitly, the default jar that is generated does not include the dependencies and they are handled by Maven normally.

Tell me if the 1.6 is OK and I will close this issue. 

Thanks

**Comment by Joholland** [comment]
:+1:
