### ISSUE TITLE
Null Pointer Exceptions

### ISSUE THREAD

**Issue by petercambal** [profesorfalken/jProcesses#23]
Hello,
I am using you library at Linux:
Linux ip-***-**-*-*** 4.9.77-31.58.amzn1.x86_64 x86_64 x86_64 x86_64 GNU/Linux

From time to time I got exception:
java.lang.NullPointerException
	at org.jutils.jprocesses.info.UnixProcessesService.parseList(UnixProcessesService.java:49)
	at org.jutils.jprocesses.info.AbstractProcessesService.getList(AbstractProcessesService.java:50)
	at org.jutils.jprocesses.info.AbstractProcessesService.getList(AbstractProcessesService.java:43)
	at org.jutils.jprocesses.info.AbstractProcessesService.getList(AbstractProcessesService.java:35)
	at org.jutils.jprocesses.JProcesses.getProcessList(JProcesses.java:136)

It would be great if you could check this issue, why is this happening and how to prevent this.

**Comment by petercambal** [comment]
Another one I am getting:
java.lang.NullPointerException
	at org.jutils.jprocesses.info.UnixProcessesService.loadFullCommandData(UnixProcessesService.java:171)
	at org.jutils.jprocesses.info.UnixProcessesService.parseList(UnixProcessesService.java:88)
	at org.jutils.jprocesses.info.AbstractProcessesService.getList(AbstractProcessesService.java:50)
	at org.jutils.jprocesses.info.AbstractProcessesService.getList(AbstractProcessesService.java:43)
	at org.jutils.jprocesses.info.AbstractProcessesService.getList(AbstractProcessesService.java:35)

**Comment by profesorfalken** [comment]
Hello, 

What happens if you launch from your bash console the following command.?:

    ps -e -o pid,command

**Comment by petercambal** [comment]
It prints list of processes, attributes processID and command. I will put a screenshot below.

![screenshot_1](https://user-images.githubusercontent.com/17699049/37914095-b37748ec-3116-11e8-8ec9-ae4e6c790f9b.png)

**Comment by profesorfalken** [comment]
Hi, 

This is weird. The only thing that can cause this NPE is an error executing the command.

Normally the stack of the IOException should be logged at severe level: 

    Logger.getLogger(ProcessesUtils.class.getName()).log(Level.SEVERE, null, ex);

Could you check if you have a log somewhere of type: "Cannot run program"... ?

Thanks

**Comment by profesorfalken** [comment]
Another question. Does it happens systematically?

I have build a new version that should give us more clues. 

If you are using maven, just add the dependency as: 

<dependency>
         <groupId>org.jprocesses</groupId>
         <artifactId>jProcesses</artifactId>
     	<version>1.6.5-SNAPSHOT</version>
  </dependency>

If not, you can download the JAR file directly from here: https://oss.sonatype.org/content/repositories/snapshots/org/jprocesses/jProcesses/1.6.5-SNAPSHOT/jProcesses-1.6.5-20180326.171140-2.jar

**Comment by petercambal** [comment]
It hapenned 24x over last 4 days, on 4 servers. Others seems fine.
I did not notice any log with "Cannot run program" message.
I am going to deploy code with new version and I will keep you updated.
